[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv

build_flags =
    -D BOARD_HAS_PSRAM
    -D TINY_GSM_MODEM_SIM7600
    -D TINY_GSM_RX_BUFFER=1024

lib_deps =
    vshymanskyy/TinyGSM
    knolleary/PubSubClient
    sparkfun/SparkFun VL53L5CX Arduino Library

monitor_filters =
    esp32_exception_decoder

